package com.daaloul.BackEnd.enums;

public enum Speciality {

    GENIE_LOGICIELLE,
    INTELIGENCE_ARTIFICIELLE ,
    RESEAUX,
    SECURITE,
    SYSTEME_EMBARQUE,
    INFORMATIQUE_INDUSTRIELLE ,
    AUTOMATIQUE,
    ELECTRONIQUE,
    TELECOMMUNICATIONS,
    GENIE_MECANIQUE,
    GENIE_CIVIL,
    GENIE_ELECTRIQUE,
    CLOUD_COMPUTING,
    BIG_DATA,
    DATA_SCIENCE,
    MACHINE_LEARNING,
    DEEP_LEARNING,
    BLOCKCHAIN,
    IOT,
    CYBER_SECURITY,
    WEB_DEVELOPMENT,
    MOBILE_DEVELOPMENT,
    GAME_DEVELOPMENT,
    INFORMATION_TECHNOLOGY
}
